version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Jerusalem
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
